# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/s2524342/Documents/Digital Design/Shifting_many_worlds/project_1/project_1.cache/wt} [current_project]
set_property parent.project_path {/home/s2524342/Documents/Digital Design/Shifting_many_worlds/project_1/project_1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{/home/s2524342/Documents/Digital Design/Shifting_many_worlds/project_1/project_1.srcs/sources_1/new/Shift_reg2D.v}}
synth_design -top Shift_reg2D -part xc7a35tcpg236-1
write_checkpoint -noxdef Shift_reg2D.dcp
catch { report_utilization -file Shift_reg2D_utilization_synth.rpt -pb Shift_reg2D_utilization_synth.pb }
