# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/s2524342/Documents/Digital Design/Timing_the_world/Timing_the_world/Timing_the_world.cache/wt} [current_project]
set_property parent.project_path {/home/s2524342/Documents/Digital Design/Timing_the_world/Timing_the_world/Timing_the_world.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{/home/s2524342/Documents/Digital Design/Timing_the_world/Timing_the_world/Timing_the_world.srcs/sources_1/imports/Timing_the_world/counter.v}}
read_xdc {{/home/s2524342/Documents/Digital Design/Timing_the_world/Timing_the_world/Timing_the_world.srcs/constrs_1/new/counter_constraints.xdc}}
set_property used_in_implementation false [get_files {{/home/s2524342/Documents/Digital Design/Timing_the_world/Timing_the_world/Timing_the_world.srcs/constrs_1/new/counter_constraints.xdc}}]

synth_design -top counter -part xc7a35tcpg236-1
write_checkpoint -noxdef counter.dcp
catch { report_utilization -file counter_utilization_synth.rpt -pb counter_utilization_synth.pb }
