# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/home/s2524342/Documents/Digital Design/Hello_Synchronous_World/Hello_Synchronous_World.cache/wt} [current_project]
set_property parent.project_path {/home/s2524342/Documents/Digital Design/Hello_Synchronous_World/Hello_Synchronous_World.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{/home/s2524342/Documents/Digital Design/Hello_Synchronous_World/Hello_Synchronous_World.srcs/sources_1/new/Shift_reg_behave.v}}
read_xdc {{/home/s2524342/Documents/Digital Design/Hello_Synchronous_World/Hello_Synchronous_World.srcs/constrs_1/new/Shift_register_constraints.xdc}}
set_property used_in_implementation false [get_files {{/home/s2524342/Documents/Digital Design/Hello_Synchronous_World/Hello_Synchronous_World.srcs/constrs_1/new/Shift_register_constraints.xdc}}]

synth_design -top Shift_reg_behave -part xc7a35tcpg236-1
write_checkpoint -noxdef Shift_reg_behave.dcp
catch { report_utilization -file Shift_reg_behave_utilization_synth.rpt -pb Shift_reg_behave_utilization_synth.pb }
